# Generated by Django 5.0.6 on 2024-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='short_description',
            field=models.CharField(default='hello', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
