# Generated by Django 5.0.6 on 2024-06-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='articles',
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='news.articles'),
        ),
    ]
