# Generated by Django 5.0.6 on 2024-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_comments_articles_comments_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='hey', max_length=50),
            preserve_default=False,
        ),
    ]
