# Generated by Django 5.0.6 on 2024-06-13 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='news.articles'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default='hey', max_length=50),
        ),
    ]
