# Generated by Django 5.0.6 on 2024-06-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_user_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
