# Generated by Django 5.0.6 on 2024-06-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_user_remove_author_user_alter_comments_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
